#task: 'spectr'
#task: 'eegs'          # eegs | spectr | eegsspectr
task: 'eegsspectr'

dataset:
  data_dir: ./dataset/
#  data_dir: ./small_eegs/
#  data_dir: ./small_spectr/
  num_classes: 6
  signal_length: 2000
  img_size: 512

train:
  save_path: "./checkpoint/"
  seed: -1
  batch_size: 32
  lr: 0.000004
  accelerator: "gpu"
  devices: 1
  max_epochs: 4
  freeze: "yes"         # yes | no
  eegs_run_name: "worthy-snowflake-208"
  spectr_run_name: "unique-frost-211"

checkpoint:
  version: 0

log:
  path: "./logs/"
  wandb: False

wandb:
  entity: martina-marino1996
  project: HMS-kaggle
  tag: ""