# task: 'eegs'          # eegs | spectr | eegsspectr
# task: 'spectr'
task: 'eegsspectr'
# task: 'eegs_cwt'

dataset:
  data_dir: ./dataset/
  num_classes: 6
  signal_length: 2000
  img_size: 512
  highcut: 60

  norm_type: mean_std # mean_std | min_max
  dataset_type: 'full'   # full | ge4 | hq 
  augmentation: 'no'  # eeg | spectr | both

  # eeg_stats: "./dataset/eeg_windows_stats.csv"
  eeg_stats: "./dataset/filtered_60Hz_eeg_windows_stats.csv"
  eeg_stats_ge4: "./dataset/filtered_60Hz_ge4_eeg_windows_stats.csv"
  eeg_stats_hq: "./dataset/filtered_60Hz_hq_eeg_windows_stats.csv"
  features_eeg_stats: "./dataset/features_eeg_stats.csv"
  features_spec_stats: "./dataset/features_spec_stats.csv"

train:
  save_path: "./checkpoint/"
  seed: -1
  batch_size: 32
  lr: 0.000004
  accelerator: "gpu"
  devices: 1
  max_epochs: 100
  freeze: False
  feat_comb_mode: 'concat'        # concat | sum | mul | w_sum_eeg | w_sum_spectr 
  # eegs_run_name: "worthy-snowflake-208" # "astral-snowball-217"
  eegs_run_name: "earthy-plant-499"    # "still-shape-233" | frosty-serenity-328
  spectr_run_name: "unique-frost-211"
  eegsspectr_run_name: "deep-star-549"  # fragrant-breeze-531 | deep-star-549 | vital-frost-279

checkpoint:
  version: 0

log:
  path: "./logs/"
  wandb: False

wandb:
  entity: martina-marino1996
  project: HMS-kaggle
  tag: ""