task: 'egg'


dataset:
  data_dir: ./dataset/
  train: ./train.csv
  val: ./val.csv
  test: ./test.csv
  num_classes: 6
  signal_length: 2000

train:
  save_path: "./models/"
  seed: -1
  batch_size: 8
  lr: 0.000004
  accelerator: "cpu"
  devices: 1
  max_epochs: 100

checkpoint:
  version: 0

log:  
  path: "./logs/"
  wandb: True

wandb:
  # entity: MarcoParola
  entity: martina-marino1996
  project: HMS-kaggle
  tag: ""
