#task: 'spectr'
task: 'eegs'          # eegs | spectr | eegs-spectr

dataset:
  data_dir: ./dataset/
#  data_dir: ./small_eegs/
#  data_dir: ./small_spectr/
  num_classes: 6
  signal_length: 2000
  img_size: 512

train:
  save_path: "./checkpoint/"
  seed: -1
  batch_size: 32
  lr: 0.000004
  accelerator: "gpu"
  devices: 1
  max_epochs: 3
  freeze: "yes"         # yes | no

checkpoint:
  version: 0

log:  
  path: "./logs/"
  wandb: True

wandb:
  entity: martina-marino1996
  project: HMS-kaggle
  tag: ""